name: activatory
description: Test data generator for Dart ecosystem. Simplifies unit testing and Test-Driven Development.
version: 1.2.2
homepage: https://github.com/syberside/Activatory

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^3.0.7

dev_dependencies:
  test: ^1.0.0
  mockito: 5.4.2
  pedantic:  ^1.9.0
